### PR TITLE
Documentation structure

### PR DESCRIPTION
**Pull request by nilshempelmann**
I moved some parts of birdhouse doc into the new one.
@cehbrecht: Do you agree?

### CODE REVIEW

**Comment by nilshempelmann** [comment]
@Zeitsperre : Would it make sence to move parts of the [birdhouse-deploy](https://birdhouse-deploy.readthedocs.io/en/latest/index.html) to the birdhouse uplevel documentation?

**Comment by Zeitsperre** [comment]
Yes, I would imagine so. Tagging @tlvu for his thoughts on what exactly.

**Review by cehbrecht — APPROVED** [review]

**Comment by cehbrecht** [comment]
@nilshempelmann I can later move the "build the docs" tutorial to somewhere else ... like a "contributing.md" file.

**Comment by tlvu** [comment]
> Yes, I would imagine so. Tagging @tlvu for his thoughts on what exactly.

Sorry for the late reply, I guess we can continue our discussion here https://github.com/bird-house/birdhouse2-docs/issues/8#issuecomment-2555506563

**Pull request merged**
